---
- name: Create temporary output directory (if missing)
  file:
    path: "/{{ temp_directory_config }}"
    state: directory
  run_once: true

- name: Clone the GIT repo
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "/{{ temp_directory_config }}/{{ repo_name }}"
  run_once: true

- name: Apply configurations
  arista.eos.eos_config:
    src: "/{{ temp_directory_config }}/{{ repo_name }}/{{ inventory_hostname }}.conf"
    replace: config
    match: none
